.Dd January  2, 2012
.Dt unaexport
.Os libuna
.Sh NAME
.Nm unaexport
.Nd exports Unicode and ASCII (byte stream) text
.Sh SYNOPSIS
.Nm unaexport
.Op Fl hvV
.Va Ar source
.Sh DESCRIPTION
.Nm unaexport
is a utility to export Unicode and ASCII (byte stream) text
.Pp
.Nm unaexport
is part of the
.Nm libuna
package.
.Nm libuna
is a library to support Unicode and ASCII (byte stream) conversions
.Pp
.Ar source
is the source device to read from.
.Pp
The options are as follows:
.Bl -tag -width Ds
.It Fl h
shows this help
.It Fl v
verbose output to stderr
.It Fl V
print version
.El
.Sh ENVIRONMENT
None
.Sh FILES
None
.Sh EXAMPLES
.Bd -literal
# unaexport -c windows-1250 -i byte_stream -o utf8 source.txt destination.txt
unaexport 20110108 (libuna 20110108)

Exporting:
	source:			source.txt
	of format:		auto detect
	destination:		destination.txt
	of format:		UTF-8
	export byte order mark:	yes
	newline conversion:	none

Export started at: Sat Jan  8 09:09:23 2011

This could take a while.

Status: exported 492 bytes
        in 0 second(s).

Export completed at: Sat Jan  8 09:09:23 2011

Exported: 492 bytes in 0 second(s).

.Ed
.Sh DIAGNOSTICS
Errors, verbose and debug output are printed to stderr when verbose output \-v is enabled.
Verbose and debug output are only printed when enabled at compilation.
.Sh BUGS
Please report bugs of any kind to <jbmetz@users.sourceforge.net> or on the project website:
http://libuna.sourceforge.net
.Sh AUTHOR
These man pages were written by Joachim Metz.
.Sh COPYRIGHT
Copyright 2008-2012 Joachim Metz <jbmetz@users.sourceforge.net>.
This is free software; see the source for copying conditions. There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

