.Dd April 10, 2019
.Dt unaexport
.Os libuna
.Sh NAME
.Nm unaexport
.Nd exports Unicode and ASCII (byte stream) text
.Sh SYNOPSIS
.Nm unaexport
.Op Fl c Ar codepage
.Op Fl i Ar input_format
.Op Fl n Ar newline_conversion
.Op Fl o Ar output_format
.Op Fl BhlqvV
.Ar source
.Sh DESCRIPTION
.Nm unaexport
is a utility to export Unicode and ASCII (byte stream) text
.Pp
.Nm unaexport
is part of the
.Nm libuna
package.
.Nm libuna
is a library to support Unicode and ASCII (byte stream) conversions
.Pp
.Ar source
is the source device to read from.
.Pp
The options are as follows:
.Bl -tag -width Ds
.It Fl B
do not export a byte order mark (BOM)
.It Fl A Ar codepage
the codepage of byte-stream, options: ascii (default), iso-8559-1, iso-8559-2, iso-8559-3, iso-8559-4, iso-8559-5, iso-8559-6, iso-8559-7, iso-8559-8, iso-8559-9, iso-8559-10, iso-8559-11, iso-8559-13, iso-8559-14, iso-8559-15, iso-8559-16, koi8-r, koi8-u, windows-874, windows-1250, windows-1251, windows-1252, windows-1253, windows-1254, windows-1255, windows-1256 windows-1257 or windows-1258
.It Fl h
shows this help
.It Fl i Ar input_format
the input format, options: auto-detect (default), utf7, utf8, utf16be, utf16le, utf32be or utf32le
.It Fl l
list information about the codepages
.It Fl n Ar newline_conversion
convert newline characters, options: none (default), cr, crlf or lf
.It Fl o Ar output_format
the output format, options: byte-stream, utf7, utf8 (default), utf16be, utf16le, utf32be or utf32le
.It Fl q
quiet shows no status information
.It Fl v
verbose output to stderr
.It Fl V
print version
.El
.Sh ENVIRONMENT
None
.Sh FILES
None
.Sh EXAMPLES
.Bd -literal
# unaexport -c windows-1250 -i byte_stream -o utf8 source.txt destination.txt
unaexport 20110108 (libuna 20110108)
.sp
Exporting:
	source:			source.txt
	of format:		auto detect
	destination:		destination.txt
	of format:		UTF-8
	export byte order mark:	yes
	newline conversion:	none
.sp
Export started at: Sat Jan  8 09:09:23 2011
.sp
This could take a while.
.sp
Status: exported 492 bytes
        in 0 second(s).
.sp
Export completed at: Sat Jan  8 09:09:23 2011
.sp
Exported: 492 bytes in 0 second(s).
.sp
.Ed
.Sh DIAGNOSTICS
Errors, verbose and debug output are printed to stderr when verbose output \-v is enabled.
Verbose and debug output are only printed when enabled at compilation.
.Sh BUGS
Please report bugs of any kind to <joachim.metz@gmail.com> or on the project website:
https://github.com/libyal/libuna/
.Sh AUTHOR
These man pages were written by Joachim Metz.
.Sh COPYRIGHT
Copyright (C) 2008-2025, Joachim Metz <joachim.metz@gmail.com>.
This is free software; see the source for copying conditions. There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
